import { NextResponse } from 'next/server';
import { connectDB } from '@/lib/mongodb';
import Product from '@/models/Product';
import User from '@/models/User';

const products = [
  {
    name: 'Highland Wildflower Honey',
    slug: 'highland-wildflower-honey',
    price: 32,
    description: 'Harvested from the remote crystalline slopes of the Northern Highlands, our Wildflower Honey is a complex tapestry of floral notes, including heather, thyme, and wild clover. This rare vintage is unfiltered and cold-pressed to preserve its natural enzymatic vitality and deep, molasses-like viscosity.',
    shortDescription: 'Complex highland wildflower blend with heather and thyme notes.',
    images: ['/placeholder-honey-1.jpg'],
    category: 'honey',
    productCollection: 'Wildflower Reserve',
    origin: 'Scottish Highlands',
    volume: ['250gm', '350gm', '500gm'],
    stock: 45,
    batchNumber: 'BATCH 042',
    tags: ['wildflower', 'highland', 'raw'],
    features: ['Certified Organic & Raw', 'Single Estate Origin: Scottish Highlands', 'Sustainably Wild-Foraged'],
    isFeatured: true,
    isRareHarvest: true,
    badge: 'RARE VINTAGE',
    rating: 5,
    reviewCount: 24,
  },
  {
    name: 'Wildflower Gold Reserve',
    slug: 'wildflower-gold-reserve',
    price: 48,
    description: 'Our signature Wildflower Gold Reserve is a carefully selected blend of highland wildflowers. Rich in antioxidants and enzymes, this honey captures the essence of untouched meadows.',
    shortDescription: 'Premium wildflower blend from protected alpine meadows.',
    images: ['/placeholder-honey-2.jpg'],
    category: 'honey',
    productCollection: 'Wildflower Reserve',
    origin: 'Alps',
    volume: ['250gm', '350gm'],
    stock: 12,
    batchNumber: 'BATCH 038',
    tags: ['wildflower', 'alpine', 'premium'],
    features: ['Cold-Pressed', 'Zero Additives', 'Alpine Origin'],
    isFeatured: true,
    isRareHarvest: false,
    rating: 5,
    reviewCount: 41,
  },
  {
    name: 'Tuscan Sun Meadow',
    slug: 'tuscan-sun-meadow',
    price: 32,
    description: 'Sourced from the sun-drenched hills of Tuscany, this golden honey carries the warm floral notes of Italian wildflowers. A bright, floral profile with citrus undertones.',
    shortDescription: 'Golden Tuscan honey with bright citrus florals.',
    images: ['/placeholder-honey-3.jpg'],
    category: 'honey',
    productCollection: 'Wildflower Reserve',
    origin: 'Tuscany',
    volume: ['250gm', '350gm', '500gm'],
    stock: 67,
    batchNumber: 'BATCH 044',
    tags: ['tuscan', 'wildflower', 'italian'],
    features: ['Single Origin', 'Unfiltered', 'Raw & Natural'],
    isFeatured: false,
    isRareHarvest: false,
    rating: 4,
    reviewCount: 18,
  },
  {
    name: 'Manuka Gold MGO 500+',
    slug: 'manuka-gold-mgo-500',
    price: 245,
    description: 'Genuine New Zealand Manuka honey with MGO 500+ certification. Renowned for its exceptional antibacterial properties and rich, earthy flavor profile.',
    shortDescription: 'Certified MGO 500+ New Zealand Manuka honey.',
    images: ['/placeholder-honey-4.jpg'],
    category: 'honey',
    productCollection: 'Highland Monofloral',
    origin: 'New Zealand',
    volume: ['250gm', '500gm'],
    stock: 8,
    batchNumber: 'BATCH 031',
    tags: ['manuka', 'mgo', 'new zealand', 'premium'],
    features: ['MGO 500+ Certified', 'UMF 20+', 'New Zealand Origin'],
    isFeatured: true,
    isRareHarvest: true,
    badge: 'BEST SELLER',
    rating: 5,
    reviewCount: 89,
  },
  {
    name: 'Black Forest Rare',
    slug: 'black-forest-rare',
    price: 68,
    description: 'Dark, resinous honeydew honey from the Black Forest. Intense malt flavors with a distinctive forest character that lingers on the palate.',
    shortDescription: 'Dark resinous honeydew from the Black Forest.',
    images: ['/placeholder-honey-5.jpg'],
    category: 'honey',
    productCollection: 'Forest Infusions',
    origin: 'Germany',
    volume: ['250gm', '350gm'],
    stock: 23,
    batchNumber: 'BATCH 029',
    tags: ['honeydew', 'forest', 'dark', 'german'],
    features: ['Honeydew Variety', 'Dark & Complex', 'Forest Origin'],
    isFeatured: true,
    isRareHarvest: false,
    badge: 'AGED 24 MONTHS',
    rating: 5,
    reviewCount: 32,
  },
  {
    name: 'Vintage Leatherwood',
    slug: 'vintage-leatherwood',
    price: 64,
    description: 'Tasmanian rarity with a unique floral bouquet. Extraordinarily viscous with a complex, spicy-sweet character found nowhere else in the world.',
    shortDescription: 'Rare Tasmanian Leatherwood with unique spicy-sweet notes.',
    images: ['/placeholder-honey-6.jpg'],
    category: 'honey',
    productCollection: 'Highland Monofloral',
    origin: 'Tasmania',
    volume: ['250gm', '350gm', '500gm'],
    stock: 15,
    batchNumber: 'BATCH 033',
    tags: ['leatherwood', 'tasmanian', 'rare'],
    features: ['Tasmanian Origin', 'Unique Floral Profile', 'Limited Edition'],
    isFeatured: false,
    isRareHarvest: true,
    rating: 5,
    reviewCount: 27,
  },
  {
    name: 'Highland White Sage',
    slug: 'highland-white-sage',
    price: 42,
    description: 'Delicate and herbal with notes of soft vanilla and peppery undertones. Harvested from California sage fields at their peak bloom.',
    shortDescription: 'Delicate sage honey with vanilla and pepper notes.',
    images: ['/placeholder-honey-7.jpg'],
    category: 'honey',
    productCollection: 'Highland Monofloral',
    origin: 'California',
    volume: ['250gm', '350gm'],
    stock: 34,
    batchNumber: 'BATCH 040',
    tags: ['sage', 'white', 'california'],
    features: ['Monofloral', 'Herb Notes', 'California Origin'],
    isFeatured: false,
    isRareHarvest: false,
    rating: 4,
    reviewCount: 15,
  },
  {
    name: 'Wild Lavender Bloom',
    slug: 'wild-lavender-bloom',
    price: 34,
    description: 'Infused with the calming scent of Provence fields. Floral, light, and delicately aromatic â€” the essence of a summer lavender field.',
    shortDescription: 'Light floral honey from Provence lavender fields.',
    images: ['/placeholder-honey-8.jpg'],
    category: 'honey',
    productCollection: 'Wildflower Reserve',
    origin: 'Provence, France',
    volume: ['250gm', '350gm', '500gm'],
    stock: 56,
    batchNumber: 'BATCH 045',
    tags: ['lavender', 'provence', 'french', 'floral'],
    features: ['Provence Origin', 'Aromatherapy Grade', 'Pure Floral'],
    isFeatured: false,
    isRareHarvest: false,
    badge: 'BEST SELLER',
    rating: 5,
    reviewCount: 63,
  },
  {
    name: 'Tupelo Blossom',
    slug: 'tupelo-blossom',
    price: 49,
    description: 'The Queen of Honey. Bright gold color with a distinct pear-like finish. Never crystallizes, harvested from the White Tupelo tree blossoms of the Georgia swamps.',
    shortDescription: 'Rare pear-finish tupelo honey that never crystallizes.',
    images: ['/placeholder-honey-9.jpg'],
    category: 'honey',
    productCollection: 'Highland Monofloral',
    origin: 'Georgia, USA',
    volume: ['250gm', '350gm'],
    stock: 19,
    batchNumber: 'BATCH 036',
    tags: ['tupelo', 'georgia', 'rare'],
    features: ['Never Crystallizes', 'Pear Finish', 'Swamp Origin'],
    isFeatured: false,
    isRareHarvest: true,
    rating: 5,
    reviewCount: 44,
  },
  {
    name: 'Raw Macadamia Comb',
    slug: 'raw-macadamia-comb',
    price: 38,
    description: 'Freshly cut honeycomb submerged in pure macadamia honey. A nutty, buttery experience that brings you straight to the hive.',
    shortDescription: 'Fresh honeycomb in macadamia honey.',
    images: ['/placeholder-honey-10.jpg'],
    category: 'honeycomb',
    productCollection: 'Forest Infusions',
    origin: 'Hawaii',
    volume: ['350gm'],
    stock: 28,
    batchNumber: 'BATCH 041',
    tags: ['macadamia', 'comb', 'hawaii', 'raw'],
    features: ['With Comb', 'Macadamia Infused', 'Hawaiian Origin'],
    isFeatured: false,
    isRareHarvest: false,
    rating: 4,
    reviewCount: 21,
  },
];

export async function GET() {
  try {
    await connectDB();

    // Seed products
    await Product.deleteMany({});
    await Product.insertMany(products);

    // Ensure admin account exists
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@beeamrit.com';
    const adminPassword = process.env.ADMIN_PASSWORD || 'admin123';
    const adminName = process.env.ADMIN_NAME || 'Admin';
    const existingAdmin = await User.findOne({ email: adminEmail });
    if (!existingAdmin) {
      await User.create({ name: adminName, email: adminEmail, password: adminPassword, role: 'admin' });
    } else if (existingAdmin.role !== 'admin') {
      existingAdmin.role = 'admin';
      await existingAdmin.save();
    }

    return NextResponse.json({
      message: `✅ Seeded ${products.length} products`,
      admin: { email: adminEmail, password: adminPassword },
    });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: 'Seed failed' }, { status: 500 });
  }
}
